# Generated by Django 5.1.15 on 2026-02-16 11:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('safety_level', models.CharField(choices=[('child', 'Kind (< 12)'), ('teen', 'Jugendlich (12-18)'), ('adult', 'Erwachsen'), ('admin', 'Administrator')], default='adult', help_text='Sicherheitsstufe für Content-Filtering', max_length=5)),
                ('is_voice_enrolled', models.BooleanField(default=False, help_text='Stimme ist registriert für Erkennung')),
                ('preferred_language', models.CharField(default='de', help_text='Bevorzugte Sprache (de, en, ...)', max_length=10)),
                ('persona_notes', models.TextField(blank=True, default='', help_text='Was SOMA über diesen Nutzer gelernt hat (Ambient Learning)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('preferred_room', models.ForeignKey(blank=True, help_text='Standard-Raum des Nutzers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.room')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'SOMA Benutzer',
                'verbose_name_plural': 'SOMA Benutzer',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_hash', models.CharField(help_text='Kryptographischer Hash des Stimm-Embeddings', max_length=512, unique=True)),
                ('pitch_mean_hz', models.FloatField(default=0.0, help_text='Durchschnittliche Grundfrequenz (Hz)')),
                ('pitch_std_hz', models.FloatField(default=0.0, help_text='Standardabweichung der Grundfrequenz (Hz)')),
                ('enrollment_samples', models.IntegerField(default=0, help_text='Anzahl der Enrollment-Samples')),
                ('last_verified', models.DateTimeField(blank=True, help_text='Letzte erfolgreiche Verifizierung', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stimmprofil',
                'verbose_name_plural': 'Stimmprofile',
            },
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('engine_used', models.CharField(default='unknown', max_length=20)),
                ('was_deferred', models.BooleanField(default=False)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('intent_category', models.CharField(blank=True, default='', help_text='Kategorie (smalltalk, device_control, question, ...)', max_length=50)),
                ('mood_detected', models.CharField(blank=True, default='', help_text='Erkannte Stimmung (neutral, happy, stressed, ...)', max_length=20)),
                ('satisfaction_signal', models.FloatField(blank=True, help_text='0-1 Zufriedenheitssignal (aus Folge-Interaktion abgeleitet)', null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaktionslog',
                'verbose_name_plural': 'Interaktionslogs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='users_inter_timesta_678855_idx'), models.Index(fields=['user', '-timestamp'], name='users_inter_user_id_af760e_idx')],
            },
        ),
    ]
