# Generated by Django 5.1.15 on 2026-02-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Eindeutiger Raumname (z.B. 'Wohnzimmer')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL-sicherer Bezeichner (z.B. 'wohnzimmer')", max_length=100, unique=True)),
                ('floor', models.IntegerField(default=0, help_text='Stockwerk (0 = EG, 1 = OG, -1 = UG)')),
                ('is_kids_room', models.BooleanField(default=False, help_text='Kinderzimmer? Aktiviert Child-Safe Mode automatisch.')),
                ('is_active', models.BooleanField(default=True, help_text='Raum ist aktiv und wird überwacht.')),
                ('description', models.TextField(blank=True, default='', help_text='Optionale Beschreibung / Notizen.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HardwareNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_id', models.CharField(help_text="Eindeutige Hardware-ID (z.B. 'mic_wohnzimmer_01')", max_length=200, unique=True)),
                ('name', models.CharField(help_text='Menschenlesbarer Name', max_length=200)),
                ('node_type', models.CharField(choices=[('mic', 'Mikrofon'), ('spk', 'Lautsprecher'), ('tab', 'Tablet'), ('sen', 'Sensor'), ('act', 'Aktor')], help_text='Gerätetyp: Mikrofon, Lautsprecher, Tablet, Sensor, Aktor', max_length=3)),
                ('protocol', models.CharField(choices=[('mqtt', 'MQTT'), ('ha', 'Home Assistant'), ('mdns', 'mDNS / Zeroconf'), ('http', 'HTTP Direct')], default='mqtt', help_text='Kommunikationsprotokoll', max_length=4)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP-Adresse (bei Netzwerk-Geräten)', null=True)),
                ('mqtt_topic', models.CharField(blank=True, default='', help_text='MQTT Topic für Kommunikation', max_length=300)),
                ('ha_entity_id', models.CharField(blank=True, default='', help_text='Home Assistant Entity-ID', max_length=300)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('degraded', 'Eingeschränkt'), ('unknown', 'Unbekannt')], default='unknown', max_length=8)),
                ('is_active', models.BooleanField(default=True, help_text='Node ist aktiv und soll verwendet werden.')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Letzter Lebenszeichens-Zeitpunkt', null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Gerätespezifische Konfiguration (JSON)')),
                ('discovered_via', models.CharField(blank=True, default='manual', help_text='Wie wurde das Gerät entdeckt? (mqtt_hello, mdns, ha, manual)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, help_text='Zugeordneter Raum', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_nodes', to='hardware.room')),
            ],
            options={
                'verbose_name': 'Hardware-Node',
                'verbose_name_plural': 'Hardware-Nodes',
                'ordering': ['room', 'node_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NodeCapability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capability', models.CharField(help_text="Fähigkeit (z.B. 'audio_input', 'display', 'temperature')", max_length=100)),
                ('direction', models.CharField(choices=[('input', 'Eingang'), ('output', 'Ausgang'), ('bidi', 'Bidirektional')], default='input', max_length=6)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Capability-spezifische Parameter (z.B. sample_rate, resolution)')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='hardware.hardwarenode')),
            ],
            options={
                'verbose_name': 'Node-Fähigkeit',
                'verbose_name_plural': 'Node-Fähigkeiten',
                'unique_together': {('node', 'capability')},
            },
        ),
        migrations.AddIndex(
            model_name='hardwarenode',
            index=models.Index(fields=['node_id'], name='hardware_ha_node_id_80053c_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwarenode',
            index=models.Index(fields=['room', 'node_type'], name='hardware_ha_room_id_5a2c24_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwarenode',
            index=models.Index(fields=['status'], name='hardware_ha_status_55e047_idx'),
        ),
    ]
